"""initial schema

Revision ID: 18255221ff8d
Revises: 
Create Date: 2026-08-11 22:07:02.361911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18255221ff8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_series',
    sa.Column('benchmark_code', sa.Text(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('index_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('benchmark_code', 'trade_date', name='pk_benchmark_series')
    )
    op.create_table('exchange_rate',
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('cash_buy', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cash_sell', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('spot_buy', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('spot_sell', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), sa.Computed('(spot_buy + spot_sell) / 2', persisted=True), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.CheckConstraint('spot_buy > 0 AND spot_sell > 0', name='ck_exchange_rate_spot_positive'),
    sa.PrimaryKeyConstraint('currency', 'rate_date', name='pk_exchange_rate')
    )
    op.create_table('industry_category',
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('industry_code', sa.Text(), nullable=False),
    sa.Column('industry_name', sa.Text(), nullable=False),
    sa.Column('industry_index_name', sa.Text(), nullable=True),
    sa.CheckConstraint("market IN ('TWSE', 'TPEX')", name='ck_industry_category_market'),
    sa.PrimaryKeyConstraint('market', 'industry_code', name='pk_industry_category')
    )
    op.create_table('login_attempt',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.CheckConstraint("outcome IN ('REJECTED_NO_IDENTITY', 'LINKED')", name='ck_login_attempt_outcome'),
    sa.CheckConstraint("provider IN ('google', 'github')", name='ck_login_attempt_provider'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_index_daily',
    sa.Column('index_name', sa.Text(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close_index', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('change_point', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('change_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('special_note', sa.Text(), server_default='', nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('index_name', 'trade_date', name='pk_market_index_daily')
    )
    op.create_index('ix_market_index_daily_trade_date', 'market_index_daily', ['trade_date'], unique=False)
    op.create_table('instrument',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('instrument_type', sa.Text(), nullable=False),
    sa.Column('industry_code', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("instrument_type IN ('STOCK', 'ETF', 'CRYPTO')", name='ck_instrument_type'),
    sa.CheckConstraint("market IN ('TWSE', 'TPEX', 'US', 'CRYPTO')", name='ck_instrument_market'),
    sa.ForeignKeyConstraint(['market', 'industry_code'], ['industry_category.market', 'industry_category.industry_code'], name='fk_instrument_industry', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'symbol', name='uq_instrument_market_symbol')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_portfolio_user_name')
    )
    op.create_table('reconciliation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('is_balanced', sa.Boolean(), nullable=False),
    sa.Column('differences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_expires_at', 'session', ['expires_at'], unique=False)
    op.create_table('user_identity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("provider IN ('google', 'github')", name='ck_user_identity_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_user_identity_provider_subject')
    )
    op.create_table('alert',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=True),
    sa.Column('rule_type', sa.Text(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(rule_type IN ('RETURN_PCT_ABOVE', 'RETURN_PCT_BELOW', 'TRAILING_STOP')) = (portfolio_id IS NOT NULL)", name='ck_alert_portfolio_scoped'),
    sa.CheckConstraint("rule_type IN ('PRICE_ABOVE', 'PRICE_BELOW', 'CHANGE_PCT_ABOVE', 'CHANGE_PCT_BELOW', 'RETURN_PCT_ABOVE', 'RETURN_PCT_BELOW', 'TRAILING_STOP', 'VOLUME_SPIKE', 'EX_DIVIDEND_AHEAD')", name='ck_alert_rule_type'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_close',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('prev_close', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('instrument_id', 'trade_date', name='pk_daily_close')
    )
    op.create_table('instrument_provider_symbol',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_symbol', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('instrument_id', 'provider', name='pk_instrument_provider_symbol'),
    sa.UniqueConstraint('provider', 'provider_symbol', name='uq_instrument_provider_symbol')
    )
    op.create_table('pending_action',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_on', sa.Date(), nullable=True),
    sa.Column('proposed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind <> 'CORPORATE_ACTION' OR portfolio_id IS NOT NULL", name='ck_pending_action_corporate_action_portfolio'),
    sa.CheckConstraint("kind IN ('CORPORATE_ACTION', 'IMPORT_CONFLICT')", name='ck_pending_action_kind'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('traded_on', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fee', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('tax', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('cash_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'SPLIT') = (ratio IS NOT NULL)", name='ck_transaction_split_ratio'),
    sa.CheckConstraint("type <> 'ADJUSTMENT' OR note IS NOT NULL", name='ck_transaction_note_required'),
    sa.CheckConstraint("type <> 'CASH_DIVIDEND' OR cash_amount IS NOT NULL", name='ck_transaction_cash_amount_required'),
    sa.CheckConstraint("type <> 'SPLIT' OR quantity IS NULL", name='ck_transaction_split_no_quantity'),
    sa.CheckConstraint("type IN ('BUY', 'SELL', 'ADJUSTMENT') OR price IS NULL", name='ck_transaction_price_forbidden'),
    sa.CheckConstraint("type IN ('BUY', 'SELL', 'CASH_DIVIDEND', 'STOCK_DIVIDEND', 'SPLIT', 'ADJUSTMENT')", name='ck_transaction_type'),
    sa.CheckConstraint("type IN ('BUY', 'SELL', 'STOCK_DIVIDEND', 'ADJUSTMENT') OR quantity IS NULL", name='ck_transaction_quantity_forbidden'),
    sa.CheckConstraint("type IN ('CASH_DIVIDEND', 'ADJUSTMENT') OR cash_amount IS NULL", name='ck_transaction_cash_amount_forbidden'),
    sa.CheckConstraint("type NOT IN ('BUY', 'SELL') OR price IS NOT NULL", name='ck_transaction_price_required'),
    sa.CheckConstraint("type NOT IN ('BUY', 'SELL', 'STOCK_DIVIDEND') OR quantity IS NOT NULL", name='ck_transaction_quantity_required'),
    sa.CheckConstraint('ratio IS NULL OR ratio > 0', name='ck_transaction_ratio_positive'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_portfolio_instrument_traded_on', 'transaction', ['portfolio_id', 'instrument_id', 'traded_on'], unique=False)
    op.create_index('ix_transaction_user_traded_on', 'transaction', ['user_id', 'traded_on'], unique=False)
    op.create_index('uq_transaction_user_external_ref', 'transaction', ['user_id', 'external_ref'], unique=True, postgresql_where=sa.text('external_ref IS NOT NULL'))
    op.create_table('alert_state',
    sa.Column('alert_id', sa.BigInteger(), nullable=False),
    sa.Column('is_armed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peak_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('peak_since', sa.Date(), nullable=True),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'SENT', 'FAILED', 'ABANDONED')", name='ck_notification_status'),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('alert_state')
    op.drop_index('uq_transaction_user_external_ref', table_name='transaction', postgresql_where=sa.text('external_ref IS NOT NULL'))
    op.drop_index('ix_transaction_user_traded_on', table_name='transaction')
    op.drop_index('ix_transaction_portfolio_instrument_traded_on', table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('pending_action')
    op.drop_table('instrument_provider_symbol')
    op.drop_table('daily_close')
    op.drop_table('alert')
    op.drop_table('user_identity')
    op.drop_index('ix_session_expires_at', table_name='session')
    op.drop_table('session')
    op.drop_table('reconciliation')
    op.drop_table('portfolio')
    op.drop_table('instrument')
    op.drop_index('ix_market_index_daily_trade_date', table_name='market_index_daily')
    op.drop_table('market_index_daily')
    op.drop_table('login_attempt')
    op.drop_table('industry_category')
    op.drop_table('exchange_rate')
    op.drop_table('benchmark_series')
    op.drop_table('app_user')
    # ### end Alembic commands ###
